### ISSUE TITLE
contribute to official repo?

### ISSUE THREAD

**Issue by guolinke** [huanzhang12/lightgbm-gpu#1]
@huanzhang12 
A awesome work !!
Do you have plan to create a PR to the official repo?

**Comment by huanzhang12** [comment]
Hi @guolinke 

It's glad to hear from you! Yes, I plan to create a PR to the official repo, hopefully by the end of this month. Currently the code is working fine for the basic use case, but I need to clean it up a little bit, fix some known small problems and do more testing.

I just created a new README.md with instructions on how to test the GPU code. I will really appreciate it if you can test it when you have time and provide some feedback. Thanks!

**Comment by huanzhang12** [comment]
GPU acceleration support has been merged into upstream LightGBM in commit [0bb4a82](https://github.com/Microsoft/LightGBM/commit/0bb4a82).
